[general]
static = yes
writeprotect = no
clearglobalvars = no

[globals]

[internal]
exten => 105,1,NoOp(Urdu AI Test Agent call)
exten => 105,2,AGI(urdu-agent.agi)
exten => 105,3,Hangup()

exten => 102,1,NoOp(AI Agent call)
same => n,Stasis(dograh)
same => n,Hangup()

exten => 9010,1,NoOp(Test)
same => n,Answer()
same => n,Playback(hello-world)
same => n,Hangup()

exten => _XXX,1,NoOp(Catch-all)
same => n,Dial(PJSIP/${EXTEN},30)
same => n,Hangup()
