#!/bin/bash
echo '========================================'
echo '  PHASE A - DATA LAYER DEPLOYMENT REPORT'
echo '========================================'
echo ''
docker ps --format 'table {{.Names}}\t{{.Status}}' --filter 'name=aios-(postgres|qdrant|redis|minio|clickhouse)'
echo ''
echo '--- Service Tests ---'
echo -n '  PostgreSQL   : '
docker exec aios-postgres pg_isready -U aios -q 2>/dev/null && echo 'healthy' || echo 'FAIL'
echo -n '  pgvector     : '
docker exec aios-postgres psql -U aios -d aios -t -c "SELECT extversion FROM pg_extension WHERE extname='vector'" 2>/dev/null | tr -d ' '
echo -n '  Qdrant       : '
curl -s -H 'api-key: aios_qdrant_2026' http://10.30.0.20:6333/collections | python3 -c "import sys,json; d=json.load(sys.stdin); print('healthy' if d.get('status')=='ok' else 'FAIL')" 2>/dev/null || echo 'FAIL'
echo -n '  Redis        : '
(echo -e 'PING\r'; sleep 1) | nc -w2 10.30.0.30 6379 2>/dev/null | head -1
echo -n '  MinIO        : '
curl -s -o /dev/null -w '%{http_code}' http://10.30.0.40:9000/minio/health/live 2>/dev/null
echo ''
echo -n '  ClickHouse   : '
docker exec aios-clickhouse clickhouse-client --query 'SELECT 1' 2>/dev/null | grep -q 1 && echo 'healthy' || echo 'FAIL'
echo ''
echo '--- Databases ---'
docker exec aios-postgres psql -U aios -d postgres -t -c 'SELECT datname FROM pg_database ORDER BY datname' 2>/dev/null | grep -v '^$'
echo ''
echo '========================================'
echo '  PHASE A - COMPLETE'
echo '========================================'
