events {}
http {
  server {
    listen 9001;
    location / {
      proxy_pass http://10.30.0.40:9001;
      proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
      proxy_set_header X-Real-IP \;
    }
  }
  server {
    listen 6333;
    location / {
      proxy_pass http://10.30.0.20:6333;
      proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
      proxy_set_header X-Real-IP \;
    }
  }
}
