#!/bin/bash
echo "============================================"
echo " AIOS — ALL SERVICE CREDENTIALS"
echo " (also stored in /aios/.env and /aios/.vault-keys)"
echo "============================================"
echo ""
echo "--- SYSTEM ---"
echo "  SSH: ai@10.0.0.100 / Lahore*999"
echo ""
echo "--- POSTGRES ---"
echo "  Host: 10.30.0.10:5432"
echo "  User: aios"
echo "  Pass: aios_secret_2026"
echo "  DBs:  aios, dograh, langfuse, litellm, keycloak"
echo ""
echo "--- MINIO (S3) ---"
echo "  URL:  https://data.socialbeesai.com/minio"
echo "  User: admin"
echo "  Pass: minioadmin"
echo ""
echo "--- GRAFANA ---"
echo "  URL:  https://monitor.socialbeesai.com/grafana"
echo "  User: admin"
echo "  Pass: grafana_admin_2026"
echo ""
echo "--- KEYCLOAK ---"
echo "  URL:  https://keycloak.socialbeesai.com"
echo "  User: admin"
echo "  Pass: admin"
echo ""
echo "--- VAULT ---"
echo "  URL:     https://vault.socialbeesai.com"
echo "  Root:    (see /aios/.vault-keys on server)"
echo "  Unseal:  (5 keys in /aios/.vault-keys)"
echo ""
echo "--- BIFROST (LiteLLM) ---"
echo "  URL:  https://ai.socialbeesai.com"
echo "  Key:  sk-aios-master-admin-key-change-me"
echo ""
echo "--- n8n ---"
echo "  URL:     https://n8n.socialbeesai.com"
echo "  Auth:    Session cookie (login via browser)"
echo "  DB Pass: 21e8c7e99182e353a7326dff9b40d4ec"
echo ""
echo "--- LANGFUSE ---"
echo "  URL:  https://langfuse.socialbeesai.com"
echo "  Auth: Create account on first visit"
echo ""
echo "--- QDRANT ---"
echo "  URL:  http://10.30.0.20:6333/dashboard"
echo "  Key:  aios_qdrant_2026"
echo ""
echo "--- PORTAINER ---"
echo "  URL:  https://monitor.socialbeesai.com/portainer"
echo "  Auth: Create admin on first visit (restart if timeout)"
echo ""
echo "--- DOGRAH ---"
echo "  URL:     https://voice.socialbeesai.com"
echo "  JWT Key: aios-dograh-jwt-secret-2026"
echo ""
echo "--- FRIGATE ---"
echo "  URL:   https://frigate.socialbeesai.com (TODO: add route)"
echo "  RTSP:  Lahore*999"
echo ""
echo "--- ASTERISK ---"
echo "  ARI:  ai / 95vt3r6ke1w8lgqg6qpcui8e"
echo "  Exts: 100-104, 9000 (passwords in .env)"
echo ""
echo "--- CROWDSEC ---"
echo "  API:  (see /aios/.env on server)"
echo ""
echo "--- TRAEFIK ---"
echo "  URL:  https://admin.socialbeesai.com"
echo ""
echo "--- CLOUDFLARE ---"
echo "  Email: admin@socialbeesai.com"
echo "  API:  (see /aios/.env on server)"
echo ""
echo "--- OPENROUTER ---"
echo "  Key: sk-or-v1-placeholder (NEEDS REAL KEY)"
echo ""
echo "============================================"
echo " NOTE: Change all default passwords in production!"
echo "============================================"
